Interface:
<Interface>:
    anchor_x: 'center'
    anchor_y: 'center'
    GridLayout:
        size_hint: None,None
        size: 500,500
        spacing: [16,11]
        cols: 3
        Button:
            size_hint: None,None
            size: 100,50
            text: '1'
            background_color:(0.24117647068,0.23333333342,0.23333333342,1)
        Button:
            size_hint: None,None
            size: 100,50
            text: '2'
            background_color:(0.34117647068,0.43333333342,0.53333333342,0.4)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,.6)

        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,1)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,0.4)

        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,1)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,.6)
        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,.6)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,0.4)
        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,.9)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,.8)

        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,.5)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,1)
        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,0.4)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,.6)

        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,1)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,0.4)

        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,1)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,.6)
        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,.6)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,0.4)
        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,.9)
        Button:
            text: '1'
            size_hint: None,None
            size: 100,50
            background_color:(0.24117647068,0.23333333342,0.23333333342,.8)

        Button:
            text: '2'
            size_hint: None,None
            size: 100,50
            background_color:(0.34117647068,0.43333333342,0.53333333342,.5)







