scroller:
<scroller>:




<StackInterface>:





<Interface>:
    #"left", "right","center"
    anchor_x: 'center'
    # "top", 'center', "bottom"
    anchor_y: 'center'
    GridLayout

        cols: 2
        size_hint: .25,.25
        Button:
            text: '1'
            size_hint: None,None
            size: 200,50
            background_color:(.3,.4,.8,.9)
        Button:
            text: '2'
            size_hint: None,None
            size: 200,50

            background_color : (.3,.4,.9,1)
        Button:
            text: '3'
            size_hint: None,None
            size: 200,50
            background_color: (.6,.3,.8,.8)

        Button:
            text: '4'
            size_hint: None,None
            size: 200,50
            background_color: (.7,.3,.8,1)





