<Interface>:
Interface:

    Button:
        text: "Blue"
        color :(1,0,0,1)
        background_color : (0,0,1,1)
        background_normal: ''
        pos: 50,200
        size: 200,100

    Button :
        text: 'Green'

        color: (0,0,1,1)
        background_color : (0,1,0,1)
        background_normal: ''
        pos: 300,200
        size: 200,100
    Button :
        text: 'Red'
        color: (0,1,0,1)
        background_color : (1,0,0,1)
        background_normal: ''
        pos: 550,200
        size: 200,100



